import type { 
  WorkflowNode, 
  Connection, 
  WorkflowTemplate 
} from "@/types/workflow";

// Re-export types for backward compatibility
export type { WorkflowNode, Connection, WorkflowTemplate };

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: "price-alert-telegram",
    name: "Price Alert to Telegram",
    description: "Get notified on Telegram when a token reaches your target price",
    category: "Notifications",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 180,
      },
      {
        id: "node-1",
        definitionId: "coinmarketcap",
        type: "node",
        title: "CoinMarketCap",
        x: 350,
        y: 180,
        config: { symbol: "BTC", condition: "above", price: "100000" },
      },
      {
        id: "node-2",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 620,
        y: 180,
        config: { message: "🚀 BTC has reached your target price!" },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
    ],
  },
  {
    id: "conditional-swap",
    name: "Conditional Token Swap",
    description: "Swap tokens based on price conditions with success/failure notifications",
    category: "DeFi",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 220,
      },
      {
        id: "node-1",
        definitionId: "coinmarketcap",
        type: "node",
        title: "CoinMarketCap",
        x: 350,
        y: 220,
        config: { symbol: "ETH", condition: "below", price: "2000" },
      },
      {
        id: "node-2",
        definitionId: "if-else",
        type: "node",
        title: "If/Else",
        x: 620,
        y: 220,
        config: { condition: "price < targetPrice" },
      },
      {
        id: "node-3",
        definitionId: "pancakeswap",
        type: "node",
        title: "PancakeSwap",
        x: 890,
        y: 140,
        config: { tokenIn: "USDT", tokenOut: "ETH", slippage: "1" },
      },
      {
        id: "node-4",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 890,
        y: 300,
        config: { message: "⏸️ Price condition not met, waiting..." },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
      { id: "conn-3", fromNode: "node-2", fromPort: 0, toNode: "node-3", toPort: 0 },
      { id: "conn-4", fromNode: "node-2", fromPort: 1, toNode: "node-4", toPort: 0 },
    ],
  },
  {
    id: "ai-analysis-trade",
    name: "AI-Powered Trading",
    description: "Use AI to analyze market conditions before executing trades",
    category: "AI",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 200,
      },
      {
        id: "node-1",
        definitionId: "coinmarketcap",
        type: "node",
        title: "CoinMarketCap",
        x: 350,
        y: 200,
        config: { symbol: "SOL" },
      },
      {
        id: "node-2",
        definitionId: "openai",
        type: "node",
        title: "OpenAI",
        x: 620,
        y: 200,
        config: { model: "gpt-4", prompt: "Analyze the current market sentiment for this token and recommend buy/sell/hold" },
      },
      {
        id: "node-3",
        definitionId: "if-else",
        type: "node",
        title: "If/Else",
        x: 890,
        y: 200,
        config: { condition: "recommendation == 'buy'" },
      },
      {
        id: "node-4",
        definitionId: "pancakeswap",
        type: "node",
        title: "PancakeSwap",
        x: 1160,
        y: 120,
        config: { tokenIn: "USDT", tokenOut: "SOL" },
      },
      {
        id: "node-5",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 1160,
        y: 280,
        config: { message: "📊 AI recommends holding position" },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
      { id: "conn-3", fromNode: "node-2", fromPort: 0, toNode: "node-3", toPort: 0 },
      { id: "conn-4", fromNode: "node-3", fromPort: 0, toNode: "node-4", toPort: 0 },
      { id: "conn-5", fromNode: "node-3", fromPort: 1, toNode: "node-5", toPort: 0 },
    ],
  },
  {
    id: "contract-monitor",
    name: "Smart Contract Monitor",
    description: "Monitor contract state and notify on changes",
    category: "Contracts",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 180,
      },
      {
        id: "node-1",
        definitionId: "read-contract",
        type: "node",
        title: "Read Contract",
        x: 350,
        y: 180,
        config: { address: "0x...", function: "totalSupply" },
      },
      {
        id: "node-2",
        definitionId: "gemini",
        type: "node",
        title: "Gemini",
        x: 620,
        y: 180,
        config: { model: "gemini-pro", prompt: "Analyze this contract data and summarize any significant changes" },
      },
      {
        id: "node-3",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 890,
        y: 180,
        config: { message: "📋 Contract update detected" },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
      { id: "conn-3", fromNode: "node-2", fromPort: 0, toNode: "node-3", toPort: 0 },
    ],
  },
  {
    id: "dca-strategy",
    name: "DCA Bot",
    description: "Dollar-cost averaging strategy with automatic swaps",
    category: "DeFi",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 180,
      },
      {
        id: "node-1",
        definitionId: "pancakeswap",
        type: "node",
        title: "PancakeSwap",
        x: 350,
        y: 180,
        config: { tokenIn: "USDT", tokenOut: "BTC", amount: "100", slippage: "0.5" },
      },
      {
        id: "node-2",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 620,
        y: 180,
        config: { message: "✅ DCA purchase completed: $100 worth of BTC" },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
    ],
  },
  {
    id: "arbitrage-detector",
    name: "Arbitrage Detector",
    description: "Detect price differences and execute arbitrage trades",
    category: "DeFi",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 200,
      },
      {
        id: "node-1",
        definitionId: "read-contract",
        type: "node",
        title: "Read Contract",
        x: 350,
        y: 120,
        config: { address: "0x...", function: "getReserves" },
      },
      {
        id: "node-2",
        definitionId: "coinmarketcap",
        type: "node",
        title: "CoinMarketCap",
        x: 350,
        y: 280,
        config: { symbol: "CAKE" },
      },
      {
        id: "node-3",
        definitionId: "openai",
        type: "node",
        title: "OpenAI",
        x: 620,
        y: 200,
        config: { prompt: "Compare DEX price vs CEX price and calculate arbitrage opportunity" },
      },
      {
        id: "node-4",
        definitionId: "if-else",
        type: "node",
        title: "If/Else",
        x: 890,
        y: 200,
        config: { condition: "profitPercentage > 0.5" },
      },
      {
        id: "node-5",
        definitionId: "pancakeswap",
        type: "node",
        title: "PancakeSwap",
        x: 1160,
        y: 120,
      },
      {
        id: "node-6",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 1160,
        y: 280,
        config: { message: "No profitable arbitrage found" },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-3", toPort: 0 },
      { id: "conn-3", fromNode: "node-3", fromPort: 0, toNode: "node-4", toPort: 0 },
      { id: "conn-4", fromNode: "node-4", fromPort: 0, toNode: "node-5", toPort: 0 },
      { id: "conn-5", fromNode: "node-4", fromPort: 1, toNode: "node-6", toPort: 0 },
    ],
  },
  {
    id: "scheduled-balance-check",
    name: "Scheduled Balance Check",
    description: "Check wallet balance on a schedule and notify if low",
    category: "Automation",
    nodes: [
      {
        id: "settings",
        definitionId: "settings",
        type: "settings",
        title: "Settings",
        x: 80,
        y: 180,
      },
      {
        id: "node-1",
        definitionId: "schedule-trigger",
        type: "node",
        title: "Schedule",
        x: 350,
        y: 180,
        config: { interval: "1h", timezone: "UTC" },
      },
      {
        id: "node-2",
        definitionId: "read-contract",
        type: "node",
        title: "Read Contract",
        x: 620,
        y: 180,
        config: { function: "balanceOf" },
      },
      {
        id: "node-3",
        definitionId: "if-else",
        type: "node",
        title: "If/Else",
        x: 890,
        y: 180,
        config: { condition: "balance < 0.1" },
      },
      {
        id: "node-4",
        definitionId: "telegram",
        type: "node",
        title: "Telegram",
        x: 1160,
        y: 100,
        config: { message: "⚠️ Low balance alert! Please top up your wallet." },
      },
    ],
    connections: [
      { id: "conn-1", fromNode: "settings", fromPort: 0, toNode: "node-1", toPort: 0 },
      { id: "conn-2", fromNode: "node-1", fromPort: 0, toNode: "node-2", toPort: 0 },
      { id: "conn-3", fromNode: "node-2", fromPort: 0, toNode: "node-3", toPort: 0 },
      { id: "conn-4", fromNode: "node-3", fromPort: 0, toNode: "node-4", toPort: 0 },
    ],
  },
];

export const getTemplatesByCategory = (): Record<string, WorkflowTemplate[]> => {
  return workflowTemplates.reduce<Record<string, WorkflowTemplate[]>>((acc, template) => {
    if (!acc[template.category]) {
      acc[template.category] = [];
    }
    acc[template.category].push(template);
    return acc;
  }, {});
};
